name: Trigger Render Deployment
on:
  push:
    branches:
      - main

jobs:
  main:
    name: Deploy to Render
    runs-on: ubuntu-latest
    steps:
      - name: Check Service ID length
        run: 'echo "Length: $(echo -n ${{ secrets.RENDER_SERVICE_ID }} | wc -c)"'