name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"

      - name: now it is
        run: |
          date=$(date +'%Y-%m-%d')
          echo "Today is $date"
          echo "date=$date" >> $GITHUB_OUTPUT

      - name: Directory content
        run: ls -l